-- ==========================================================
-- BRENNTAG - PRODUTO, ENDEREÇO, PAGAMENTO E DESCONTO NÃO ACUMULATIVO
-- Execute depois dos patches anteriores do projeto.
-- ==========================================================

begin;

-- ----------------------------------------------------------
-- 1) CÓDIGO DO PRODUTO
-- ----------------------------------------------------------

alter table public.products
  add column if not exists product_code text;

update public.products
set product_code = 'PRD-' || lpad(id::text, 5, '0')
where product_code is null or btrim(product_code) = '';

create unique index if not exists products_product_code_uidx
  on public.products (lower(btrim(product_code)))
  where product_code is not null and btrim(product_code) <> '';

-- ----------------------------------------------------------
-- 2) FORMAS DE PAGAMENTO
-- ----------------------------------------------------------

create table if not exists public.payment_methods (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.payment_methods (code, name, active, sort_order)
values
  ('pix', 'Pix', true, 1),
  ('credit', 'Cartão de crédito', true, 2),
  ('boleto', 'Boleto bancário', true, 3)
on conflict (code) do update
set name = excluded.name,
    sort_order = excluded.sort_order;

alter table public.payment_methods enable row level security;

drop policy if exists "payment_methods_active_select" on public.payment_methods;
create policy "payment_methods_active_select"
on public.payment_methods
for select
to authenticated
using (active = true or public.is_admin());

drop policy if exists "payment_methods_admin_all" on public.payment_methods;
create policy "payment_methods_admin_all"
on public.payment_methods
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

grant select on public.payment_methods to authenticated;

create or replace function public.admin_set_payment_method(
  p_code text,
  p_active boolean
)
returns boolean
language plpgsql
security definer
set search_path = public
as $function$
begin
  if not public.is_admin() then
    raise exception 'Apenas administradores podem alterar formas de pagamento.';
  end if;

  update public.payment_methods
  set active = coalesce(p_active, false),
      updated_at = now()
  where code = lower(trim(coalesce(p_code, '')));

  if not found then
    raise exception 'Forma de pagamento não encontrada.';
  end if;

  return true;
end;
$function$;

revoke all on function public.admin_set_payment_method(text, boolean) from public;
grant execute on function public.admin_set_payment_method(text, boolean) to authenticated;

-- ----------------------------------------------------------
-- 3) ENDEREÇO E PAGAMENTO NO PEDIDO
-- ----------------------------------------------------------

alter table public.orders
  add column if not exists shipping_cep text,
  add column if not exists shipping_state text,
  add column if not exists shipping_city text,
  add column if not exists shipping_street text,
  add column if not exists shipping_number text,
  add column if not exists shipping_neighborhood text,
  add column if not exists shipping_complement text,
  add column if not exists payment_method text,
  add column if not exists payment_method_name text;

-- Nova versão do checkout. Mantém create_order(jsonb, integer) intacta.
create or replace function public.create_order(
  p_items jsonb,
  p_terms_version integer,
  p_shipping_cep text,
  p_shipping_state text,
  p_shipping_city text,
  p_shipping_street text,
  p_shipping_number text,
  p_shipping_neighborhood text,
  p_shipping_complement text,
  p_payment_method text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_order_id bigint;
  v_payment_code text;
  v_payment_name text;
begin
  if auth.uid() is null then
    raise exception 'Usuário não autenticado.';
  end if;

  v_payment_code := lower(trim(coalesce(p_payment_method, '')));

  select code, name
  into v_payment_code, v_payment_name
  from public.payment_methods
  where code = v_payment_code
    and active = true
  limit 1;

  if v_payment_name is null then
    raise exception 'A forma de pagamento selecionada não está disponível.';
  end if;

  if p_shipping_cep is null or trim(p_shipping_cep) !~ '^[0-9]{5}-?[0-9]{3}$' then
    raise exception 'CEP inválido.';
  end if;

  if p_shipping_state is null or upper(trim(p_shipping_state)) !~ '^[A-Z]{2}$' then
    raise exception 'Estado inválido.';
  end if;

  if nullif(trim(p_shipping_city), '') is null then
    raise exception 'Cidade é obrigatória.';
  end if;

  if nullif(trim(p_shipping_street), '') is null then
    raise exception 'Rua é obrigatória.';
  end if;

  if nullif(trim(p_shipping_number), '') is null then
    raise exception 'Número é obrigatório.';
  end if;

  if nullif(trim(p_shipping_neighborhood), '') is null then
    raise exception 'Bairro é obrigatório.';
  end if;

  v_order_id := public.create_order(p_items, p_terms_version);

  update public.orders
  set shipping_cep = regexp_replace(trim(p_shipping_cep), '[^0-9]', '', 'g'),
      shipping_state = upper(trim(p_shipping_state)),
      shipping_city = trim(p_shipping_city),
      shipping_street = trim(p_shipping_street),
      shipping_number = trim(p_shipping_number),
      shipping_neighborhood = trim(p_shipping_neighborhood),
      shipping_complement = nullif(trim(coalesce(p_shipping_complement, '')), ''),
      payment_method = v_payment_code,
      payment_method_name = v_payment_name,
      updated_at = now()
  where id = v_order_id;

  return v_order_id;
end;
$function$;

revoke all on function public.create_order(
  jsonb, integer, text, text, text, text, text, text, text, text
) from public;

grant execute on function public.create_order(
  jsonb, integer, text, text, text, text, text, text, text, text
) to authenticated;

-- ----------------------------------------------------------
-- 4) DESCONTOS NÃO ACUMULAM
-- O cliente recebe somente o maior entre:
--   a) faixa progressiva
--   b) cupom
-- ----------------------------------------------------------

create or replace function public.apply_discount_coupon(
  p_order_id bigint,
  p_code text
)
returns table(
  coupon_code text,
  discount_percent numeric,
  subtotal numeric,
  discount_amount numeric,
  total numeric
)
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_coupon public.discount_coupons%rowtype;
  v_customer uuid;
  v_status public.order_status;
  v_subtotal numeric(12,2);
  v_progressive numeric(12,2);
  v_progressive_percent numeric(5,2);
  v_discount numeric(12,2);
  v_total numeric(12,2);
  v_existing_coupon text;
begin
  if auth.uid() is null then
    raise exception 'Usuário não autenticado.';
  end if;

  select o.customer_id,
         o.status,
         o.coupon_code,
         coalesce(o.progressive_discount_amount,0),
         coalesce(o.progressive_discount_percent,0)
  into v_customer, v_status, v_existing_coupon, v_progressive, v_progressive_percent
  from public.orders as o
  where o.id = p_order_id
  for update;

  if not found then raise exception 'Pedido não encontrado.'; end if;
  if v_customer <> auth.uid() and not public.is_admin() then
    raise exception 'Você não pode aplicar cupom neste pedido.';
  end if;
  if v_status = 'Cancelado' then
    raise exception 'Este pedido já foi cancelado.';
  end if;
  if v_existing_coupon is not null then
    raise exception 'Este pedido já possui um cupom aplicado.';
  end if;

  select *
  into v_coupon
  from public.discount_coupons
  where upper(code) = upper(trim(coalesce(p_code,'')))
  for update;

  if not found then raise exception 'Cupom não encontrado.'; end if;
  if not v_coupon.active then raise exception 'Este cupom está desativado.'; end if;
  if v_coupon.expires_at is not null and v_coupon.expires_at < now() then
    raise exception 'Este cupom expirou.';
  end if;
  if v_coupon.max_uses is not null and v_coupon.uses_count >= v_coupon.max_uses then
    raise exception 'Este cupom atingiu o limite de usos.';
  end if;

  select round(coalesce(sum(quantity * unit_price),0),2)
  into v_subtotal
  from public.order_items
  where order_id = p_order_id;

  if v_subtotal <= 0 then
    raise exception 'Não foi possível calcular o subtotal do pedido.';
  end if;

  v_discount := round(v_subtotal * v_coupon.discount_percent / 100, 2);

  if v_progressive >= v_discount then
    raise exception 'Este cupom não supera o desconto progressivo atual. Os descontos não são acumulados.';
  end if;

  v_total := greatest(0, round(v_subtotal - v_discount, 2));

  update public.orders
  set subtotal = v_subtotal,
      progressive_discount_percent = 0,
      progressive_discount_amount = 0,
      coupon_code = upper(v_coupon.code),
      discount_percent = v_coupon.discount_percent,
      discount_amount = v_discount,
      total = v_total,
      updated_at = now()
  where id = p_order_id;

  update public.discount_coupons
  set uses_count = uses_count + 1,
      updated_at = now()
  where id = v_coupon.id;

  return query
    select upper(v_coupon.code),
           v_coupon.discount_percent,
           v_subtotal,
           v_discount,
           v_total;
end;
$function$;

grant execute on function public.apply_discount_coupon(bigint, text) to authenticated;

commit;
