-- ==========================================================
-- BRENNTAGHUB - FRETES + OBSERVAÇÃO + PEDIDO DETALHADO
-- Execute depois de:
--   1) brenntag_checkout_product_payment_patch.sql
--   2) brenntag_progressive_discount_reviews_patch.sql
-- ==========================================================

begin;

alter table public.orders
  add column if not exists shipping_method_id bigint,
  add column if not exists shipping_method_name text,
  add column if not exists shipping_amount numeric(12,2) not null default 0,
  add column if not exists shipping_free boolean not null default false,
  add column if not exists order_note text;

create table if not exists public.shipping_methods (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null default 0,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shipping_settings (
  id integer primary key default 1,
  free_shipping_enabled boolean not null default false,
  free_shipping_minimum numeric(12,2) not null default 0,
  updated_at timestamptz not null default now(),
  constraint shipping_settings_singleton check (id = 1)
);

insert into public.shipping_settings (id) values (1)
on conflict (id) do nothing;

insert into public.shipping_methods (name, price, active, sort_order)
select seed.name, seed.price, seed.active, seed.sort_order
from (values
  ('Econômico',15.00::numeric,true,1),
  ('Padrão',25.00::numeric,true,2),
  ('Expresso',40.00::numeric,true,3)
) as seed(name,price,active,sort_order)
where not exists (select 1 from public.shipping_methods);

do $$
begin
  if not exists (select 1 from pg_constraint where conname='orders_shipping_method_id_fkey') then
    alter table public.orders add constraint orders_shipping_method_id_fkey
      foreign key (shipping_method_id) references public.shipping_methods(id) on delete set null;
  end if;
end $$;

create index if not exists idx_shipping_methods_active_order
  on public.shipping_methods(active,sort_order);

create index if not exists idx_orders_shipping_method_id
  on public.orders(shipping_method_id);

alter table public.shipping_methods enable row level security;
alter table public.shipping_settings enable row level security;

drop policy if exists "shipping methods public read" on public.shipping_methods;
create policy "shipping methods public read"
on public.shipping_methods for select to anon,authenticated
using (active=true or public.is_admin());

drop policy if exists "shipping settings public read" on public.shipping_settings;
create policy "shipping settings public read"
on public.shipping_settings for select to anon,authenticated
using (true);

create or replace function public.admin_update_shipping_method(
  p_id bigint,p_name text,p_price numeric,p_active boolean
) returns public.shipping_methods
language plpgsql security definer set search_path=public
as $$
declare v_row public.shipping_methods;
begin
  if not public.is_admin() then raise exception 'Apenas administradores podem alterar fretes.'; end if;
  if p_name is null or btrim(p_name)='' or p_price is null or p_price<0 then
    raise exception 'Dados de frete inválidos.';
  end if;
  update public.shipping_methods
  set name=btrim(p_name),price=round(p_price,2),active=coalesce(p_active,true),updated_at=now()
  where id=p_id returning * into v_row;
  if not found then raise exception 'Frete não encontrado.'; end if;
  return v_row;
end;
$$;

create or replace function public.admin_create_shipping_method(
  p_name text,p_price numeric,p_active boolean default true
) returns public.shipping_methods
language plpgsql security definer set search_path=public
as $$
declare v_row public.shipping_methods; v_sort integer;
begin
  if not public.is_admin() then raise exception 'Apenas administradores podem alterar fretes.'; end if;
  if p_name is null or btrim(p_name)='' or p_price is null or p_price<0 then
    raise exception 'Dados de frete inválidos.';
  end if;
  select coalesce(max(sort_order),0)+1 into v_sort from public.shipping_methods;
  insert into public.shipping_methods(name,price,active,sort_order)
  values(btrim(p_name),round(p_price,2),coalesce(p_active,true),v_sort)
  returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.admin_delete_shipping_method(p_id bigint)
returns boolean language plpgsql security definer set search_path=public
as $$
begin
  if not public.is_admin() then raise exception 'Apenas administradores podem alterar fretes.'; end if;
  delete from public.shipping_methods where id=p_id;
  if not found then raise exception 'Frete não encontrado.'; end if;
  return true;
end;
$$;

create or replace function public.admin_update_shipping_settings(
  p_enabled boolean,p_minimum numeric
) returns public.shipping_settings
language plpgsql security definer set search_path=public
as $$
declare v_row public.shipping_settings;
begin
  if not public.is_admin() then raise exception 'Apenas administradores podem alterar fretes.'; end if;
  if p_minimum is null or p_minimum<0 then raise exception 'Valor mínimo inválido.'; end if;
  update public.shipping_settings
  set free_shipping_enabled=coalesce(p_enabled,false),
      free_shipping_minimum=round(p_minimum,2),updated_at=now()
  where id=1 returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.create_order(
  p_items jsonb,p_terms_version integer,
  p_shipping_cep text,p_shipping_state text,p_shipping_city text,
  p_shipping_street text,p_shipping_number text,p_shipping_neighborhood text,
  p_shipping_complement text,p_shipping_method_id bigint,p_order_note text,
  p_payment_method text
)
returns bigint language plpgsql security definer set search_path=public
as $$
declare
  v_order_id bigint;
  v_payment_code text;
  v_payment_name text;
  v_method public.shipping_methods%rowtype;
  v_subtotal numeric(12,2);
  v_shipping numeric(12,2);
  v_free boolean;
begin
  if auth.uid() is null then raise exception 'Usuário não autenticado.'; end if;

  v_payment_code=lower(trim(coalesce(p_payment_method,'')));
  select code,name into v_payment_code,v_payment_name
  from public.payment_methods where code=v_payment_code and active=true limit 1;
  if v_payment_name is null then raise exception 'A forma de pagamento selecionada não está disponível.'; end if;

  if p_shipping_cep is null or trim(p_shipping_cep)!~'^[0-9]{5}-?[0-9]{3}$' then raise exception 'CEP inválido.'; end if;
  if p_shipping_state is null or upper(trim(p_shipping_state))!~'^[A-Z]{2}$' then raise exception 'Estado inválido.'; end if;
  if nullif(trim(p_shipping_city),'') is null then raise exception 'Cidade é obrigatória.'; end if;
  if nullif(trim(p_shipping_street),'') is null then raise exception 'Rua é obrigatória.'; end if;
  if nullif(trim(p_shipping_number),'') is null then raise exception 'Número é obrigatório.'; end if;
  if nullif(trim(p_shipping_neighborhood),'') is null then raise exception 'Bairro é obrigatório.'; end if;

  select * into v_method from public.shipping_methods where id=p_shipping_method_id and active=true;
  if not found then raise exception 'A modalidade de frete selecionada não está disponível.'; end if;

  v_order_id=public.create_order(p_items,p_terms_version);

  select round(coalesce(sum(quantity*unit_price),0),2) into v_subtotal
  from public.order_items where order_id=v_order_id;

  v_free=exists(
    select 1 from public.shipping_settings
    where id=1 and free_shipping_enabled=true and v_subtotal>=free_shipping_minimum
  );
  v_shipping=case when v_free then 0 else round(v_method.price,2) end;

  update public.orders set
    shipping_cep=regexp_replace(trim(p_shipping_cep),'[^0-9]','','g'),
    shipping_state=upper(trim(p_shipping_state)),
    shipping_city=trim(p_shipping_city),
    shipping_street=trim(p_shipping_street),
    shipping_number=trim(p_shipping_number),
    shipping_neighborhood=trim(p_shipping_neighborhood),
    shipping_complement=nullif(trim(coalesce(p_shipping_complement,'')),''),
    payment_method=v_payment_code,
    payment_method_name=v_payment_name,
    shipping_method_id=v_method.id,
    shipping_method_name=v_method.name,
    shipping_amount=v_shipping,
    shipping_free=v_free,
    order_note=nullif(left(trim(coalesce(p_order_note,'')),500),''),
    total=round(coalesce(total,0)+v_shipping,2),
    updated_at=now()
  where id=v_order_id;

  return v_order_id;
end;
$$;

create or replace function public.apply_progressive_order_discount(p_order_id bigint)
returns boolean language plpgsql security definer set search_path=public
as $$
declare
  v_customer uuid; v_status public.order_status;
  v_subtotal numeric(12,2); v_percent numeric(5,2):=0;
  v_discount numeric(12,2):=0; v_coupon_discount numeric(12,2):=0;
  v_shipping numeric(12,2):=0;
begin
  if auth.uid() is null then raise exception 'Usuário não autenticado.'; end if;
  select customer_id,status,coalesce(shipping_amount,0)
  into v_customer,v_status,v_shipping from public.orders where id=p_order_id for update;
  if not found then raise exception 'Pedido não encontrado.'; end if;
  if v_customer<>auth.uid() and not public.is_admin() then raise exception 'Você não pode alterar este pedido.'; end if;
  if v_status='Cancelado' then raise exception 'Este pedido já foi cancelado.'; end if;

  select round(coalesce(sum(quantity*unit_price),0),2) into v_subtotal
  from public.order_items where order_id=p_order_id;

  select discount_percent into v_percent
  from public.cart_discount_tiers where active=true and min_value<=v_subtotal
  order by min_value desc limit 1;

  v_percent=coalesce(v_percent,0);
  v_discount=round(v_subtotal*v_percent/100,2);
  v_coupon_discount=round(coalesce((select discount_amount from public.orders where id=p_order_id),0),2);

  update public.orders set
    subtotal=v_subtotal,
    progressive_discount_percent=v_percent,
    progressive_discount_amount=v_discount,
    total=greatest(0,round(v_subtotal-v_discount-v_coupon_discount+v_shipping,2)),
    updated_at=now()
  where id=p_order_id;
  return true;
end;
$$;

create or replace function public.apply_discount_coupon(
  p_order_id bigint,p_code text
)
returns table(coupon_code text,discount_percent numeric,subtotal numeric,discount_amount numeric,total numeric)
language plpgsql security definer set search_path=public
as $$
declare
  v_coupon public.discount_coupons%rowtype;
  v_customer uuid; v_status public.order_status;
  v_subtotal numeric(12,2); v_progressive numeric(12,2);
  v_coupon_base numeric(12,2); v_discount numeric(12,2);
  v_total numeric(12,2); v_shipping numeric(12,2);
  v_existing_coupon text;
begin
  if auth.uid() is null then raise exception 'Usuário não autenticado.'; end if;

  select o.customer_id,o.status,o.coupon_code,
         coalesce(o.progressive_discount_amount,0),coalesce(o.shipping_amount,0)
  into v_customer,v_status,v_existing_coupon,v_progressive,v_shipping
  from public.orders o where o.id=p_order_id for update;

  if not found then raise exception 'Pedido não encontrado.'; end if;
  if v_customer<>auth.uid() and not public.is_admin() then raise exception 'Você não pode aplicar cupom neste pedido.'; end if;
  if v_status='Cancelado' then raise exception 'Este pedido já foi cancelado.'; end if;
  if v_existing_coupon is not null then raise exception 'Este pedido já possui um cupom aplicado.'; end if;

  select * into v_coupon from public.discount_coupons
  where upper(code)=upper(trim(coalesce(p_code,''))) for update;
  if not found then raise exception 'Cupom não encontrado.'; end if;
  if not v_coupon.active then raise exception 'Este cupom está desativado.'; end if;
  if v_coupon.expires_at is not null and v_coupon.expires_at<now() then raise exception 'Este cupom expirou.'; end if;
  if v_coupon.max_uses is not null and v_coupon.uses_count>=v_coupon.max_uses then raise exception 'Este cupom atingiu o limite de usos.'; end if;

  select round(coalesce(sum(quantity*unit_price),0),2) into v_subtotal
  from public.order_items where order_id=p_order_id;
  if v_subtotal<=0 then raise exception 'Não foi possível calcular o subtotal do pedido.'; end if;

  v_coupon_base=greatest(0,v_subtotal-v_progressive);
  v_discount=round(v_coupon_base*v_coupon.discount_percent/100,2);
  v_total=greatest(0,round(v_subtotal-v_progressive-v_discount+v_shipping,2));

  update public.orders set
    subtotal=v_subtotal,coupon_code=upper(v_coupon.code),
    discount_percent=v_coupon.discount_percent,discount_amount=v_discount,
    total=v_total,updated_at=now()
  where id=p_order_id;

  update public.discount_coupons set uses_count=uses_count+1,updated_at=now() where id=v_coupon.id;
  return query select upper(v_coupon.code),v_coupon.discount_percent,v_subtotal,v_discount,v_total;
end;
$$;

revoke all on function public.admin_update_shipping_method(bigint,text,numeric,boolean) from public;
revoke all on function public.admin_create_shipping_method(text,numeric,boolean) from public;
revoke all on function public.admin_delete_shipping_method(bigint) from public;
revoke all on function public.admin_update_shipping_settings(boolean,numeric) from public;
revoke all on function public.create_order(jsonb,integer,text,text,text,text,text,text,text,bigint,text,text) from public;
revoke all on function public.apply_progressive_order_discount(bigint) from public;
revoke all on function public.apply_discount_coupon(bigint,text) from public;

grant execute on function public.admin_update_shipping_method(bigint,text,numeric,boolean) to authenticated;
grant execute on function public.admin_create_shipping_method(text,numeric,boolean) to authenticated;
grant execute on function public.admin_delete_shipping_method(bigint) to authenticated;
grant execute on function public.admin_update_shipping_settings(boolean,numeric) to authenticated;
grant execute on function public.create_order(jsonb,integer,text,text,text,text,text,text,text,bigint,text,text) to authenticated;
grant execute on function public.apply_progressive_order_discount(bigint) to authenticated;
grant execute on function public.apply_discount_coupon(bigint,text) to authenticated;

notify pgrst,'reload schema';
commit;
