-- BrenntagHub - Sistema de fretes
-- Execute este arquivo no Supabase SQL Editor.

create table if not exists public.shipping_methods (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null default 0,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shipping_settings (
  id integer primary key default 1,
  free_shipping_enabled boolean not null default false,
  free_shipping_minimum numeric(12,2) not null default 0,
  updated_at timestamptz not null default now(),
  constraint shipping_settings_singleton check (id = 1)
);

insert into public.shipping_settings (id)
values (1)
on conflict (id) do nothing;

insert into public.shipping_methods (name, price, active, sort_order)
select *
from (
  values
    ('Econômico', 15.00, true, 1),
    ('Padrão', 25.00, true, 2),
    ('Expresso', 40.00, true, 3)
) as seed(name, price, active, sort_order)
where not exists (select 1 from public.shipping_methods);

alter table public.orders
  add column if not exists shipping_method_id bigint,
  add column if not exists shipping_method_name text,
  add column if not exists shipping_amount numeric(12,2) not null default 0,
  add column if not exists shipping_free boolean not null default false;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'orders_shipping_method_id_fkey'
  ) then
    alter table public.orders
      add constraint orders_shipping_method_id_fkey
      foreign key (shipping_method_id)
      references public.shipping_methods(id)
      on delete set null;
  end if;
end $$;

create index if not exists idx_shipping_methods_active_order
  on public.shipping_methods(active, sort_order);

create index if not exists idx_orders_shipping_method_id
  on public.orders(shipping_method_id);

alter table public.shipping_methods enable row level security;
alter table public.shipping_settings enable row level security;

drop policy if exists "shipping methods public read" on public.shipping_methods;
create policy "shipping methods public read"
on public.shipping_methods
for select
to anon, authenticated
using (active = true);

drop policy if exists "shipping settings public read" on public.shipping_settings;
create policy "shipping settings public read"
on public.shipping_settings
for select
to anon, authenticated
using (true);

-- Observação:
-- O frontend/Admin deverá usar as funções administrativas já existentes
-- ou funções SECURITY DEFINER para alterar fretes/configurações.
-- Os valores do frete escolhido ficam gravados no pedido, para que
-- alterações futuras não mudem pedidos antigos.
