-- ==========================================================
-- BRENNTAGHUB — DESCONTO PROGRESSIVO + AVALIAÇÕES DE COMPRA
-- Rode no Supabase SQL Editor depois dos patches atuais.
-- ==========================================================

begin;

-- ----------------------------------------------------------
-- 1) DESCONTOS PROGRESSIVOS
-- ----------------------------------------------------------

create table if not exists public.cart_discount_tiers (
  id bigint generated by default as identity primary key,
  min_value numeric(14,2) not null check (min_value >= 0),
  discount_percent numeric(5,2) not null check (discount_percent >= 0 and discount_percent <= 100),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cart_discount_tiers_active_value_idx
  on public.cart_discount_tiers(active, min_value);

insert into public.cart_discount_tiers (min_value, discount_percent, active)
select 500, 2, true
where not exists (select 1 from public.cart_discount_tiers);

insert into public.cart_discount_tiers (min_value, discount_percent, active)
select 1000, 4, true
where not exists (select 1 from public.cart_discount_tiers where min_value = 1000);

insert into public.cart_discount_tiers (min_value, discount_percent, active)
select 2000, 6, true
where not exists (select 1 from public.cart_discount_tiers where min_value = 2000);

insert into public.cart_discount_tiers (min_value, discount_percent, active)
select 5000, 8, true
where not exists (select 1 from public.cart_discount_tiers where min_value = 5000);

alter table public.orders
  add column if not exists progressive_discount_percent numeric(5,2) not null default 0,
  add column if not exists progressive_discount_amount numeric(12,2) not null default 0;

create or replace function public.preview_progressive_cart_discount(p_subtotal numeric)
returns table(
  min_value numeric,
  discount_percent numeric,
  discount_amount numeric,
  total numeric,
  next_min_value numeric,
  next_discount_percent numeric
)
language sql
security definer
stable
set search_path = public
as $$
  with current_tier as (
    select t.min_value, t.discount_percent
    from public.cart_discount_tiers t
    where t.active = true
      and t.min_value <= greatest(coalesce(p_subtotal,0),0)
    order by t.min_value desc
    limit 1
  ),
  next_tier as (
    select t.min_value, t.discount_percent
    from public.cart_discount_tiers t
    where t.active = true
      and t.min_value > greatest(coalesce(p_subtotal,0),0)
    order by t.min_value asc
    limit 1
  )
  select
    coalesce(c.min_value,0)::numeric,
    coalesce(c.discount_percent,0)::numeric,
    round(greatest(coalesce(p_subtotal,0),0) * coalesce(c.discount_percent,0) / 100,2)::numeric,
    round(greatest(coalesce(p_subtotal,0),0) * (1 - coalesce(c.discount_percent,0) / 100),2)::numeric,
    n.min_value,
    n.discount_percent
  from current_tier c
  full join next_tier n on true;
$$;

create or replace function public.apply_progressive_order_discount(p_order_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer uuid;
  v_status public.order_status;
  v_subtotal numeric(12,2);
  v_percent numeric(5,2) := 0;
  v_discount numeric(12,2) := 0;
  v_coupon_discount numeric(12,2) := 0;
begin
  if auth.uid() is null then
    raise exception 'Usuário não autenticado.';
  end if;

  select customer_id, status
  into v_customer, v_status
  from public.orders
  where id = p_order_id
  for update;

  if not found then raise exception 'Pedido não encontrado.'; end if;
  if v_customer <> auth.uid() and not public.is_admin() then
    raise exception 'Você não pode alterar este pedido.';
  end if;
  if v_status = 'Cancelado' then raise exception 'Este pedido já foi cancelado.'; end if;

  select round(coalesce(sum(quantity * unit_price),0),2)
  into v_subtotal
  from public.order_items
  where order_id = p_order_id;

  select discount_percent
  into v_percent
  from public.cart_discount_tiers
  where active = true and min_value <= v_subtotal
  order by min_value desc
  limit 1;

  v_percent := coalesce(v_percent,0);
  v_discount := round(v_subtotal * v_percent / 100,2);
  v_coupon_discount := round(coalesce((select discount_amount from public.orders where id=p_order_id),0),2);

  update public.orders
  set subtotal = v_subtotal,
      progressive_discount_percent = v_percent,
      progressive_discount_amount = v_discount,
      total = greatest(0, round(v_subtotal - v_discount - v_coupon_discount,2)),
      updated_at = now()
  where id = p_order_id;

  return true;
end;
$$;

create or replace function public.admin_save_progressive_tiers(p_tiers jsonb)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  v_id bigint;
  v_min numeric(14,2);
  v_percent numeric(5,2);
  v_active boolean;
begin
  if not public.is_admin() then
    raise exception 'Apenas administradores podem alterar as faixas.';
  end if;

  if p_tiers is null or jsonb_typeof(p_tiers) <> 'array' then
    raise exception 'Faixas inválidas.';
  end if;

  delete from public.cart_discount_tiers;

  for item in select * from jsonb_array_elements(p_tiers) loop
    v_id := nullif(item->>'id','')::bigint;
    v_min := round(coalesce((item->>'min_value')::numeric,0),2);
    v_percent := round(coalesce((item->>'discount_percent')::numeric,0),2);
    v_active := coalesce((item->>'active')::boolean,true);

    if v_min < 0 or v_percent < 0 or v_percent > 100 then
      raise exception 'Uma das faixas possui valores inválidos.';
    end if;

    insert into public.cart_discount_tiers(min_value, discount_percent, active)
    values(v_min,v_percent,v_active);
  end loop;

  return true;
end;
$$;

revoke all on function public.preview_progressive_cart_discount(numeric) from public;
revoke all on function public.apply_progressive_order_discount(bigint) from public;
revoke all on function public.admin_save_progressive_tiers(jsonb) from public;

grant execute on function public.preview_progressive_cart_discount(numeric) to authenticated;
grant execute on function public.apply_progressive_order_discount(bigint) to authenticated;
grant execute on function public.admin_save_progressive_tiers(jsonb) to authenticated;

-- ----------------------------------------------------------
-- 2) CUPOM + DESCONTO PROGRESSIVO
-- O cupom passa a ser calculado sobre o valor já reduzido
-- pelo desconto progressivo.
-- ----------------------------------------------------------

create or replace function public.apply_discount_coupon(
  p_order_id bigint,
  p_code text
)
returns table(
  coupon_code text,
  discount_percent numeric,
  subtotal numeric,
  discount_amount numeric,
  total numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_coupon public.discount_coupons%rowtype;
  v_customer uuid;
  v_status public.order_status;
  v_subtotal numeric(12,2);
  v_progressive numeric(12,2);
  v_coupon_base numeric(12,2);
  v_discount numeric(12,2);
  v_total numeric(12,2);
  v_existing_coupon text;
begin
  if auth.uid() is null then raise exception 'Usuário não autenticado.'; end if;

  select o.customer_id, o.status, o.coupon_code,
         coalesce(o.progressive_discount_amount,0)
  into v_customer, v_status, v_existing_coupon, v_progressive
  from public.orders as o
  where o.id=p_order_id
  for update;

  if not found then raise exception 'Pedido não encontrado.'; end if;
  if v_customer <> auth.uid() then raise exception 'Você não pode aplicar cupom neste pedido.'; end if;
  if v_status='Cancelado' then raise exception 'Este pedido já foi cancelado.'; end if;
  if v_existing_coupon is not null then raise exception 'Este pedido já possui um cupom aplicado.'; end if;

  select * into v_coupon
  from public.discount_coupons
  where upper(code)=upper(trim(coalesce(p_code,'')))
  for update;

  if not found then raise exception 'Cupom não encontrado.'; end if;
  if not v_coupon.active then raise exception 'Este cupom está desativado.'; end if;
  if v_coupon.expires_at is not null and v_coupon.expires_at < now() then raise exception 'Este cupom expirou.'; end if;
  if v_coupon.max_uses is not null and v_coupon.uses_count >= v_coupon.max_uses then raise exception 'Este cupom atingiu o limite de usos.'; end if;

  select round(coalesce(sum(quantity * unit_price),0),2)
  into v_subtotal
  from public.order_items
  where order_id=p_order_id;

  if v_subtotal <= 0 then raise exception 'Não foi possível calcular o subtotal do pedido.'; end if;

  v_coupon_base := greatest(0, v_subtotal - v_progressive);
  v_discount := round(v_coupon_base * v_coupon.discount_percent / 100,2);
  v_total := greatest(0, round(v_subtotal - v_progressive - v_discount,2));

  update public.orders
  set subtotal=v_subtotal,
      coupon_code=upper(v_coupon.code),
      discount_percent=v_coupon.discount_percent,
      discount_amount=v_discount,
      total=v_total,
      updated_at=now()
  where id=p_order_id;

  update public.discount_coupons
  set uses_count=uses_count+1, updated_at=now()
  where id=v_coupon.id;

  return query
    select upper(v_coupon.code), v_coupon.discount_percent, v_subtotal, v_discount, v_total;
end;
$$;

grant execute on function public.apply_discount_coupon(bigint,text) to authenticated;

-- ----------------------------------------------------------
-- 3) AVALIAÇÕES DE COMPRA
-- ----------------------------------------------------------

create table if not exists public.order_reviews (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  customer_id uuid not null references auth.users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text not null default '' check (char_length(comment) <= 1000),
  created_at timestamptz not null default now()
);

create index if not exists order_reviews_customer_idx
  on public.order_reviews(customer_id);

create index if not exists order_reviews_order_idx
  on public.order_reviews(order_id);

alter table public.order_reviews enable row level security;

drop policy if exists "order_reviews_customer_select" on public.order_reviews;
create policy "order_reviews_customer_select"
on public.order_reviews
for select
to authenticated
using (customer_id = auth.uid() or public.is_admin());

drop policy if exists "order_reviews_admin_select" on public.order_reviews;
create policy "order_reviews_admin_select"
on public.order_reviews
for select
to authenticated
using (public.is_admin());

create or replace function public.submit_order_review(
  p_order_id bigint,
  p_rating integer,
  p_comment text default ''
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer uuid;
  v_status public.order_status;
begin
  if auth.uid() is null then raise exception 'Usuário não autenticado.'; end if;
  if p_rating is null or p_rating < 1 or p_rating > 5 then
    raise exception 'A nota deve estar entre 1 e 5.';
  end if;

  select customer_id, status
  into v_customer, v_status
  from public.orders
  where id = p_order_id;

  if not found then raise exception 'Pedido não encontrado.'; end if;
  if v_customer <> auth.uid() then raise exception 'Você só pode avaliar suas próprias compras.'; end if;
  if v_status <> 'Concluído' then
    raise exception 'A avaliação só pode ser enviada depois que o pedido for concluído.';
  end if;

  if exists (select 1 from public.order_reviews where order_id = p_order_id) then
    raise exception 'Este pedido já foi avaliado.';
  end if;

  insert into public.order_reviews(order_id, customer_id, rating, comment)
  values(p_order_id, auth.uid(), p_rating, left(coalesce(trim(p_comment),''),1000));

  return true;
end;
$$;

revoke all on function public.submit_order_review(bigint,integer,text) from public;
grant execute on function public.submit_order_review(bigint,integer,text) to authenticated;

notify pgrst, 'reload schema';

commit;
